Task1
daniilpyatko/HashMap pull request #1
Opened 2020-05-30 19:36 UTC by daniilpyatko

2020-05-30 20:01 UTC, daniilpyatko commented
ID посылки: 31596431

2020-05-30 21:23 UTC, glebshp requested changes
Местами надо сделать логику выполнения более плоской. Чем меньше вложенность, тем лучше. Больше используй пустые строки для разделения логических блоков

2020-05-30 21:23 UTC, glebshp commented on HashMap.cpp
> +//  HashMap that uses the rescaling technique to maintain the
Нет описания какой именно тип хеш-таблицы, открытая адресация или цепочки, какая схема используется для линейного итерирования

2020-05-30 21:23 UTC, glebshp commented on HashMap.cpp
> +  HashMap& operator=(const HashMap& h1) {
плохое имя аргумента

2020-05-30 21:23 UTC, glebshp commented on HashMap.cpp
> +        found = true;
Почему просто не сделать тут return?

2020-05-30 21:23 UTC, glebshp commented on HashMap.cpp
> +      if (cnt_elements_ > capacity_ * kExpand) {
Нужно сделать отдельный метод, который будет проверять, требуется ли rebuild, и вызывать его если нужно

2020-05-30 21:23 UTC, glebshp commented on HashMap.cpp
> +        found = true;
опять же, почему не return?

2020-05-30 21:23 UTC, glebshp commented on HashMap.cpp
> +      insert({x, ValueType()});
вот тут очень неэффективно, нужно сделать insert, который сразу возвращает результат find

2020-06-09 22:11 UTC, glebshp requested changes
С прошлого раза остались незакрытые issue

2020-06-09 22:11 UTC, glebshp commented on HashMap.cpp
> +    for (size_t i = 0; i < capacity_; ++i) {
зачем вот это делать, почему не swap?

2020-06-09 22:11 UTC, glebshp commented on HashMap.cpp
> +    return kAfterEndPos;
что-то не то с отступами, две подряд закрывающие скобки на одном уровне

2020-06-09 22:11 UTC, glebshp commented on HashMap.cpp
> +  ValueType& operator[](KeyType x) {
Тут плохо, что если элемента нет, то мы сделаем два вычисления хеша (на поиск и на вставку), хотя могли бы обойтись одним

2020-06-14 15:31 UTC, daniilpyatko commented on HashMap.cpp
> +  ValueType& operator[](KeyType x) {
Изначально пытался сделать через std::optional, но получил CE при подключении нужной библиотеки, видимо, нет C++17.

2020-06-14 15:31 UTC, daniilpyatko commented
ID посылки: 33476395

2020-06-19 23:34 UTC, glebshp requested changes

2020-06-19 23:34 UTC, glebshp commented on HashMap.cpp
> +//  HashMap that uses separate chaining(open hashing) for collision resolution.
как это одновременно separate chaining и open hashing?

2020-06-19 23:34 UTC, glebshp commented on HashMap.cpp
> +
зачем тут целых 3 пустых строки подряд?

2020-06-19 23:34 UTC, glebshp commented on HashMap.cpp
> +#include <stdexcept>
Ты делаешь шаблонный класс в .h, почему тут .cpp ?

2020-06-19 23:34 UTC, glebshp commented on HashMap.cpp
> +using namespace std;
в библиотечном .h не может быть using namespace

2020-06-21 00:30 UTC, glebshp approved these changes

2020-06-21 06:40 UTC, merged